name: Build on Windows

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # Checkout submodules

    - name: Generate Solution using Protobuild
      run: .\Protobuild.exe
      shell: cmd # Use cmd shell for .exe execution
      working-directory: ./labnation_decoders_repo # Run in submodule directory

    # --- Remove failed Chocolatey step ---
    # - name: Install .NET Framework 4.0 Developer Pack
    #  run: choco install microsoft-net-framework-4.0-developer-pack -y --no-progress # Yet another package name attempt
    #  shell: pwsh
    # ----------------------------------------------------

    # --- Add step to install .NET 4.0 Targeting Pack via VS Installer ---
    - name: Install .NET Framework 4.0 Targeting Pack
      run: | 
        & "${env:ProgramFiles(x86)}/Microsoft Visual Studio/Installer/vs_installer.exe" modify `
          --installPath "${env:ProgramFiles}/Microsoft Visual Studio/2022/Enterprise" `
          --add Microsoft.Net.Component.4.TargetingPack `
          --quiet --norestart --nocache --wait
      shell: pwsh
    # -------------------------------------------------------------------

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild Decoders.Windows.sln /p:Configuration=Release # Removed FrameworkPathOverride
      working-directory: ./labnation_decoders_repo 
      shell: cmd # Use cmd shell for MSBuild
      # Note: Assumes Protobuild generates 'LabNation.Decoders.sln'.
      # This filename might need adjustment if Protobuild uses a different name.

    # Optional: Add steps here to upload build artifacts (DLLs) if needed
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: decoder-dlls
    #     path: |
    #       **/bin/Release/*.dll # Adjust this path based on actual build output locations 